project:
  type: website

website:
  title: "Global Demography"
  sidebar:
    style: "docked"
    background: light
    search: true
    pinned: true
    contents:
      - href: index.qmd
        text: Home
      - href: migration lecture.qmd
        text: Migration Lecture 
      - href: basic methods.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

