project:
  type: website
  output-dir: docs

website:
  title: "Global Demography"
  sidebar:
    style: "docked"
    background: light
    search: true
    pinned: true
    contents:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: migration lecture.qmd
        text: Migration Lecture 
      - href: basic methods.qmd
        text: Basic Methods 
      - href: fertility.qmd
        text: fertility

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

