---
title: "Basic Methods"
---

# Session 1

# Session 2

# Session 3

# Session 4

# Session 5

# 5.11. Session 6

## Fertility and Reproduction

Period TFR = average number of children who would be born to a hypothetical cohort of women

Assumptions:

-   if they had all survived to the end of their reproductive period

-   bear children at each age at the rate observed during a particular period

### Reproductive measures

-   TFR \> 2.1 -\> population is growing

-   TFR \< 2.1 -\> population

TFR as growth indicator ignores two factors: sex ratio and mortality

Comparing the sizes of successive generations (comparing #daughters and #mothers) -\> ASFR using female births

$$
nF_x^f = \frac{\# \text{female births to women age }[x, x + n]}{\text{PYL of women age }[x, x + n]}
$$

#### Gross Reproduction Rate

GRR = number of daughters an average women would have if she lived through the end of their reproductive span

#### Net Reproduction Rate

= total number of daughter each member of a birth cohort of women produce during their reproduction life span if they were subject to the observed ASFR and ASMR

-\> NRR is simply GRR adjusted or mortality

GRR and NRR:

$l_0$ = original size of the women birth cohort

$nL_x^f$ = PYL by members of the cohort of women in age interval $[x, x+n]$

$nF_x^f * nL_x^f$ = number of daughters born to between $[x,x+n]$ to a birth cohort of women

Average number of daughters born to a cohort of size $l_0$

$$ NRR = \frac{\sum{F_i^F * nL_x^f}}{l_0}$$ ????

-   If NRR \> 1, cohort of girls will replace a bigger cohort of daughters than themselves
-   If NRR = 1, the next generation will be exactly the same size as the present one
-   If NRR \< 1, implies that each generation is smaller than the previous generation, so the population will decline from natural decline across the generations

::: callout-note
The stable population assumption is crucial when interpreting the NRR, meaning it is assumed that the structure of a population does not change over time.

-   Constant fertility and mortality rates
:::

### Parity Progression Ratio

The parity progression ratio measures proportion of women with $n$ children who go on to have $n+1$ children.

-   What proportion of women

-   ???

#### Calculating PRR

$W$ ... original cohort size

$W_j$ ... #women at parity $i$

$W = \sum_{j = 0}^{I}{W_j}$

$P_j$ ... #women at parity $j$ or more

$P_j = \sum_{a= j}^{I}{W_a}$

$$ PRR_{j, j+1} = \frac{\text{Women at Parity j + 1 or more }}{\text{Women at Parity j or more}} = \frac{P_{j+1}}{P_j}$$

### Completed cohort fertility 

$$
CCF = \sum_{i = 1}{PPR(0,i)}
$$

### Order Specific TFR 

Birth order refers to the rank of a birth according to the number of previous births to the mother.

$$
F_{i, j, t} = \frac{\text{#births of order j to women in age group i}}{}
$$

2 sections

short essays about basic concepts, definitions, simple data for calculations, limitations of crude rates eg

real data, like Sweden case, summary indicators, life table, similar to homework
