---
title: "Migration lecture"
---

## 4.11. Lecture 1

### Why is migration important?

Individual

-   improvement, adaptation

Cities, regions, countries

-   future size, needs & characteristics

-   depopulation

-   brain drain/gain

-   size of labour force

-   integration issues

Global development

-   transfer of manpower and skills

-   greater occupational specialization

-   needed knowledge for global growth

-   higher overall economic productivity

::: callout-note
### Definitions:

Closed population = population without migration flows, only births and deaths

Open population = affected by births, deaths, immigration and emigration

Population change = natural increase + net migration

Net migration = immigration - emigration
:::

### Migration in Demography:

-   change in size of population

-   migrants may have different mortality and fertility rates

-   different characteristics: age structure, sex ratio, education

### Definitions of Migration

A universally accepted definition of a migrant does not exist at international level. (country of birth, citizenship, past addresses, etc.)

::: callout-note
### Definition of Migration according to IOM:

Migration is the movement of persons away from their **place of usual residence**, either across an international border or within a state, to a new residence.
:::

::: callout-note
### UN Definition of usual place of residence

The place at which the person lives at the time of the census and has been there for some time and intends to stay there for some time.
:::

UN recommends a threshold of 12 months when considering place of usual residence.

::: callout-note
### Definition of migration (Yusuf et al. 2014)

Spatial movement of a person which requires:

-   a change in place

-   involves crossing political/administrative border
:::

### Types of migration

????

::: callout-note
### Voluntary migration

voluntary migration = whether the migrant has a choice whether or not to migrate and where to migrate

e.g: labour, family, students, irregular
:::

::: callout-note
### Forced migration

forced migration = when people are obliged to flee or to leave their homes or places of habitual residence because of a conflict, disaster etc.

e.g: refugees, asylum seekers displaced persons, environmental migrants, trafficking
:::

refugee = person who fled their country or ????

asylum seeker = seeking international protection ???

Forms/types of migration

-   border: international, internal

-   duration: long term, short term

-   order: regular irregular displacement (forced)

-   reason: economic, political, environmental, family etc.

Internal migrant

= moves from a residence in one state/province/district etc. across a border

????

out-migrant/ in-migrant

international migration ????

immigrant/emigration

### Intra-EU mobility

### Duration of stay

???? definitions

### Mobility vs. Migration

::: callout-note
### Mobility

mobility = refers to the transitory movements of people in the course of their everyday lives
:::

migration = permanent change of residence

### Order of Migration

::: callout-note
### Order (IOM, 2021)

regular = occurs in compliance with laws of the country of origin, transit, and destination

irregular = movement takes place outside the laws, regulations and international agreements, includes refugees, victims of trafficking unaccompanied migrant children

displacement (forced) = movement of persons have been forced or obliged to flee in order to avoid the effects of armed conflict, situations of generalized violence, human rights violations, natural human-made disasters
:::

### Reasons for migration

-   education

-   work

-   family

-   asylum

Socio-economic migration = movement of people to benefit from greater economic opportunities

In 2017 2/3 of international migrants are migrant workers, 70% live in high-income countries

Political migrants = forced to migrate because of (civil) war, state policies which discriminate, opression

humanitarian refugees =

Environmental migrant = forced to leave for reasons of sudden or progressive changes in the environment, which affect lives and living conditions

trapped popilation =

family reunification

### Stocks and Flows

stocks = #total international migrants living in a country at a particular point in time

flow =
